version: "2.4"

services:
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:3.1.0
    mem_limit: 256m
    container_name: hive-postgresql
    restart: always 
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - cluster

  master-node:
    image: sporule/big-data-cluster:master-node
    mem_limit: 2048m
    container_name: master-node
    restart: always 
    ports:
      - 10000:9870
      - 10001:10086
      - 10002:9999
      - 10003:8083
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - hadoop_historyserver:/hadoop/yarn/timeline
      - landing_zone:/landing_zone
      - master_node_root:/root/
    environment:
      - AIRFLOW=0
      - ZOOKEEPER=0
      - KAFKA=0
    env_file:
      - ./hadoop.env
    networks:
      - cluster

  worker-node01:
    image: sporule/big-data-cluster:worker-node
    mem_limit: 6000m
    container_name: worker-node01
    restart: always 
    volumes:
      - worker-node01:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - cluster    

  worker-node02:
    image: sporule/big-data-cluster:worker-node
    mem_limit: 6000m
    container_name: worker-node02
    restart: always 
    volumes:
      - worker-node02:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - cluster

  dev-node01:
    image: sporule/big-data-cluster:dev-node
    mem_limit: 2048m
    container_name: dev-node01
    restart: always 
    ports:
      - "10012:22"
      - "10010:8080"
      - "10011:8081"
      - "10013:8083"
      - "10014:8998"
      
    volumes:
      - dev-node01_root:/root/
      - dev-node01_home:/home/
      - share_folder:/root/share/
      - landing_zone:/root/landing_zone
    environment:
        - AIRFLOW=0
        - NIFI=0
        - LIVY=0
        - JUPYTER=1
    env_file:
      - ./hadoop.env
    networks:
      - cluster

volumes:
  postgres:
  master_node_root:
  hadoop_namenode:
  worker-node01:
  worker-node02:
  landing_zone:
  hadoop_historyserver:
  dev-node01_root:
  dev-node01_home:
  share_folder:
networks:
  cluster:
    name: cluster
