version: "2.4"

services:
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:3.1.0
    mem_limit: 256m
    container_name: hive-postgresql
    restart: always 
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - cluster

  master-node:
    image: sporule/big-data-cluster:master-node
    mem_limit: 2048m
    container_name: master-node
    restart: always 
    ports:
      - 9870:9870
      - 9000:9000
      - 8188:8188
      - 10086:10086
      - 9080:8080
      - 10000:10000
      - 10002:10002
      - 2181:2181
      - 9092:9092
      - 9999:9999
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - hadoop_historyserver:/hadoop/yarn/timeline
      - landing_zone:/landing_zone
      - master_node_root:/root/
    environment:
      - AIRFLOW=0
      - ZOOKEEPER=0
      - KAFKA=0
    env_file:
      - ./hadoop.env
    networks:
      - cluster

  worker-node01:
    image: sporule/big-data-cluster:worker-node
    mem_limit: 6500m
    container_name: worker-node01
    restart: always 
    ports:
      - 8042:8042
      - 9864:9864
    volumes:
      - worker-node01:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - cluster    

  worker-node02:
    image: sporule/big-data-cluster:worker-node
    mem_limit: 6500m
    container_name: worker-node02
    restart: always 
    ports:
      - 8043:8042
      - 9865:9864
    volumes:
      - worker-node02:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - cluster

  worker-node03:
    image: sporule/big-data-cluster:worker-node
    mem_limit: 6500m
    container_name: worker-node03
    restart: always 
    ports:
      - 8044:8042
      - 9866:9864
    volumes:
      - worker-node03:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - cluster

  worker-node04:
    image: sporule/big-data-cluster:worker-node
    mem_limit: 6500m
    container_name: worker-node04
    restart: always 
    ports:
      - 8045:8042
      - 9867:9864
    volumes:
      - worker-node04:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - cluster

  dev-node01:
    image: sporule/big-data-cluster:dev-node
    mem_limit: 480m
    container_name: dev-node01
    restart: always 
    ports:
      - "10022:22"
      - "10110:8080"
    volumes:
      - dev-node01_root:/root/
      - share_folder:/root/share/
    environment:
        - AIRFLOW=0
        - JUPYTER=0
    env_file:
      - ./hadoop.env
    networks:
      - cluster
  
  dev-node02:
    image: sporule/big-data-cluster:dev-node
    mem_limit: 480m
    container_name: dev-node02
    restart: always 
    ports:
      - "10023:22"
      - "10111:8080"
    volumes:
      - dev-node02_root:/root/
      - share_folder:/root/share/
    environment:
        - AIRFLOW=0
        - JUPYTER=0
    env_file:
      - ./hadoop.env
    networks:
      - cluster

  dev-node03:
    image: sporule/big-data-cluster:dev-node
    mem_limit: 480m
    container_name: dev-node03
    restart: always 
    ports:
      - "10024:22"
      - "10112:8080"
    volumes:
      - dev-node03_root:/root/
      - share_folder:/root/share/
    environment:
        - AIRFLOW=0
        - JUPYTER=0
    env_file:
      - ./hadoop.env
    networks:
      - cluster
  
  dev-node04:
    image: sporule/big-data-cluster:dev-node
    mem_limit: 480m
    container_name: dev-node04
    restart: always 
    ports:
      - "10025:22"
      - "10113:8080"
    volumes:
      - dev-node04_root:/root/
      - share_folder:/root/share/
    environment:
        - AIRFLOW=0
        - JUPYTER=1
    env_file:
      - ./hadoop.env
    networks:
      - cluster

volumes:
  postgres:
  master_node_root:
  hadoop_namenode:
  worker-node01:
  worker-node02:
  worker-node03:
  worker-node04:
  landing_zone:
  hadoop_historyserver:
  dev-node01_root:
  dev-node02_root:
  dev-node03_root:
  dev-node04_root:
  share_folder:
networks:
  cluster:
    name: cluster
