version: "3.5"

services:
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:3.1.0
    container_name: hive-postgresql
    ports:
      - 5432:5432

  master-node:
    image: de214de746e1
    container_name: master-node
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
      - 8188:8188
      - 8088:8088
      - 10000:10000
      - 10002:10002
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "hive-metastore-postgresql:5432"
    command: /opt/hive/bin/hive --service metastore
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  worker-node01:
  worker-node02:
  dev-node01:
  hadoop_historyserver:
networks:
  default:
    name: datahub2
