version: "3.5"

services:
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:3.1.0
    container_name: hive-postgresql
    ports:
      - 5432:5432

  master-node:
    image: 62a3756ca546
    container_name: master-node
    ports:
      - 9870:9870
      - 9000:9000
      - 8188:8188
      - 8088:8088
      - 10000:10000
      - 10002:10002
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

  worker-node01:
    image: 3c06c31f1d81
    container_name: worker-node01
    ports:
      - 8042:8042
      - 9864:9864
    volumes:
      - worker-node01:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  worker-node02:
    image: 3c06c31f1d81
    container_name: worker-node02
    ports:
      - 8043:8042
      - 9865:9864
    volumes:
      - worker-node02:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  dev-node01:
    image: sporule/big-data-cluster:dev-node
    container_name: dev-node01
    volumes:
      - dev-node01:/workspace
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  worker-node01:
  worker-node02:
  dev-node01:
  hadoop_historyserver:
networks:
  default:
    name: cluster
