version: "2.4"

services:
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:3.1.0
    mem_limit: 256m
    container_name: hive-postgresql
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - cluster

  master-node:
    image: sporule/big-data-cluster:master-node
    mem_limit: 2048m
    container_name: master-node
    ports:
      - 9870:9870
      - 9000:9000
      - 8188:8188
      - 10086:10086
      - 9080:8080
      - 10000:10000
      - 10002:10002
      - 2181:2181
      - 9092:9092
      - 9999:9999
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - hadoop_historyserver:/hadoop/yarn/timeline
      - landing_zone:/landing_zone
      - master_node_root:/root/
    environment:
      - AIRFLOW=0
      - ZOOKEEPER=0
      - KAFKA=0
    env_file:
      - ./hadoop.env
    networks:
      - cluster

  worker-node01:
    image: sporule/big-data-cluster:worker-node
    mem_limit: 5000m
    container_name: worker-node01
    ports:
      - 8042:8042
      - 9864:9864
    volumes:
      - worker-node01:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - cluster    

  worker-node02:
    image: sporule/big-data-cluster:worker-node
    mem_limit: 5000m
    container_name: worker-node02
    ports:
      - 8043:8042
      - 9865:9864
    volumes:
      - worker-node02:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - cluster

  dev-node01:
    image: sporule/big-data-cluster:dev-node
    mem_limit: 2048m
    container_name: dev-node01
    ports:
      - "10022:22"
      - 10080:8080
    volumes:
      - dev-node01_root:/root/
      - landing_zone:/landing_zone/
    environment:
        - AIRFLOW=0
    env_file:
      - ./hadoop.env
    networks:
      - cluster

volumes:
  postgres:
  master_node_root:
  hadoop_namenode:
  worker-node01:
  worker-node02:
  landing_zone:
  dev-node01_root:
  hadoop_historyserver:
networks:
  cluster:
    name: cluster